version: "3"

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: githubprofiles-web
        hostname: githubprofiles-web
        ports: 
            - 5560:80