# Build app image
FROM node:14-alpine as build

WORKDIR /usr/app
COPY package.json package-lock.json ./

RUN npm ci --silent

COPY . .

RUN npm run build

# Production enviroment
FROM nginx:stable-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]